// Generated by CoffeeScript 1.10.0
(function() {
  var CSON, fs, namespace, path, postcss;

  fs = require('fs');

  path = require('path');

  CSON = require('cson');

  postcss = require('postcss');

  namespace = postcss.plugin('postcss-namespace', function(opts) {
    if (opts == null) {
      opts = {
        token: '-'
      };
    }
    return function(css) {
      var namespaces, target;
      namespaces = [];
      css.walkAtRules('namespace', function(rule) {
        var line, nextLine;
        namespace = rule.params;
        line = rule.source.start.line;
        if (namespaces.length === 0) {
          namespaces.push({
            namespace: namespace,
            line: line,
            nextLine: null
          });
        } else {
          nextLine = rule.source.start.line;
          namespaces[namespaces.length - 1].nextLine = nextLine;
          namespaces.push({
            namespace: namespace,
            line: line,
            nextLine: null
          });
        }
        return rule.remove();
      });
      if (namespaces.length !== 0) {
        target = namespaces.shift();
        return css.walkRules(function(rule) {
          var handler, re, selector;
          if ((target.nextLine != null) && target.nextLine < rule.source.start.line) {
            target = namespaces.shift();
          }
          selector = rule.selector;
          re = /^([#\.])([^\s\[]+)/g;
          handler = function(m, idOrClass, name) {
            if (target.namespace) {
              return idOrClass + target.namespace + opts.token + name;
            } else {
              return idOrClass + name;
            }
          };
          return rule.selector = selector.replace(re, handler);
        });
      }
    };
  });

  module.exports = namespace;

}).call(this);
